Hw02 fix app
n0more/otus_hw pull request #2
Opened 2024-10-18 17:51 UTC by n0more

2024-10-18 18:00 UTC, vladislavmass requested changes

2024-10-18 18:00 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Если мы не смогли открыть файл, значит нам и читать нечего. Поэтому тут нужно выйти из функции, уведомив вызывающий код об ошибки. `return nil,err`

2024-10-18 18:00 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Вызывающий код необходимо уведомить что при вызове функции произошла ошибка. `return nil,err`

2024-10-18 18:00 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
> +		return nil, nil
Вызывающий код необходимо уведомить что при вызове функции произошла ошибка. `return nil,err`

2024-10-18 18:00 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  	res := data
Эта строка не имеет никакого смысла. Можно сразу вернуть data

2024-10-18 22:02 UTC, n0more commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Спасибо, поправил.

2024-10-19 03:44 UTC, vladislavmass approved these changes

2024-10-30 17:49 UTC, merged